# Generated by Django 6.0.3 on 2026-03-24 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_bags', models.IntegerField()),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('acres', models.FloatField()),
                ('crop_type', models.CharField(max_length=100)),
                ('total_bags', models.IntegerField()),
                ('total_amount', models.FloatField(default=0)),
                ('lorry_number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='farmers/')),
            ],
        ),
        migrations.CreateModel(
            name='HarvesterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=100)),
                ('machine_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='harvest_files/')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('operator_name', models.CharField(default='NA', max_length=100)),
                ('machine_number', models.CharField(default='NA', max_length=10)),
                ('acres', models.FloatField()),
                ('time', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('bill', models.ImageField(upload_to='bills/')),
            ],
        ),
        migrations.CreateModel(
            name='MillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('mill_name', models.CharField(max_length=200)),
                ('mill_address', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('paddy_type', models.CharField(max_length=200)),
                ('bags', models.CharField(max_length=100)),
                ('lorry', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mills/')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Farmer', 'Farmer'), ('Mill', 'Mill')], max_length=20)),
                ('crop', models.CharField(max_length=50)),
                ('bags', models.IntegerField()),
                ('amount', models.FloatField()),
                ('lorry', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='paddy_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HarvesterFarmerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('acres', models.FloatField()),
                ('total_time', models.CharField(max_length=50)),
                ('total_amount', models.IntegerField()),
                ('harvester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='core.harvesterentry')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
