# Generated by Django 6.0.3 on 2026-03-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_farmerentry_total_bags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvesterOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=100)),
                ('machine_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('farmer_name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('acres', models.FloatField()),
                ('total_time', models.CharField(max_length=50)),
                ('total_amount', models.FloatField()),
                ('bill', models.ImageField(blank=True, null=True, upload_to='harvester_bills/')),
            ],
        ),
        migrations.RemoveField(
            model_name='harvesterfarmerdetail',
            name='harvester',
        ),
        migrations.DeleteModel(
            name='HarvesterEntry',
        ),
        migrations.DeleteModel(
            name='HarvesterFarmerDetail',
        ),
    ]
