# Generated by Django 6.0.3 on 2026-03-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_harvesteroperator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('farmer_name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MillTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mill_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
